/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "portabledeviceapi.h"

/* Header for class com_github_hms11rn_Mtp */

#ifndef _Included_com_github_hms11rn_Mtp
#define _Included_com_github_hms11rn_Mtp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hms11rn_Mtp
 * Method:    registerJNI
 */
JNIEXPORT void JNICALL Java_com_github_hms11rn_mtp_Mtp_registerJNI
  (JNIEnv *);

#ifdef __cplusplus
}
#endif
#endif


void handleException(const char* type, const char* name, HRESULT hr);
jobject ConvertUnsignedLongLongToJava(JNIEnv* env, ULONGLONG number);