/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_github_hms11rn_Mtp */

#ifndef _Included_com_github_hms11rn_Mtp
#define _Included_com_github_hms11rn_Mtp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hms11rn_Mtp
 * Method:    getMtpNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_hms11rn_mtp_Mtp_getMtpNames
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

void handleException(char* name);